/**
 * The garage. Every vehicle here is an original design - proportions, names and
 * marques are invented for this game and are not modelled on any real car.
 */

import type {
  CarDefinition,
  CarStats,
  UpgradeDefinition,
  UpgradeId,
} from './types';

export const CARS: CarDefinition[] = [
  /* ------------------------------ STARTERS ------------------------------ */
  {
    id: 'kestrel-rs',
    name: 'Kestrel RS',
    make: 'Vantis',
    carClass: 'sport',
    price: 0,
    unlockLevel: 0,
    blurb: 'Light, honest and forgiving. The car every Apex Trace career starts in.',
    stats: {
      topSpeed: 66,
      acceleration: 68,
      braking: 72,
      handling: 80,
      grip: 76,
      weight: 1180,
      downforce: 34,
      drift: 52,
      nitro: 0,
    },
    design: {
      length: 4.32,
      width: 1.84,
      height: 1.28,
      rideHeight: 0.13,
      cabinCenter: 0.56,
      cabinLength: 1.62,
      cabinWidth: 1.44,
      cabinRise: 0.3,
      noseTaper: 0.68,
      tailTaper: 0.82,
      flare: 0.1,
      wheelRadius: 0.33,
      wheelWidth: 0.24,
      frontAxle: -1.32,
      rearAxle: 1.34,
      wing: 1,
      wingWidth: 1.5,
      wingHeight: 0.1,
      sideIntakes: false,
      roofScoop: false,
      diffuser: false,
      splitter: true,
      lights: 'slim',
      canopy: 'fastback',
      stripe: 'center',
    },
    defaults: {
      primary: '#d94f2b',
      secondary: '#101318',
      finish: 'gloss',
      wheelStyle: 'split5',
      wheelColor: '#20242c',
      decal: 'stripes',
      raceNumber: 7,
      spoiler: false,
      tint: true,
    },
  },
  {
    id: 'civetta-e',
    name: 'Civetta E',
    make: 'Orlo',
    carClass: 'city',
    price: 4800,
    unlockLevel: 0,
    blurb: 'Tiny electric hatch. Absurd agility, almost no top end.',
    stats: {
      topSpeed: 52,
      acceleration: 74,
      braking: 68,
      handling: 88,
      grip: 72,
      weight: 1020,
      downforce: 18,
      drift: 44,
      nitro: 0,
    },
    design: {
      length: 3.72,
      width: 1.72,
      height: 1.46,
      rideHeight: 0.16,
      cabinCenter: 0.5,
      cabinLength: 1.72,
      cabinWidth: 1.4,
      cabinRise: 0.42,
      noseTaper: 0.84,
      tailTaper: 0.92,
      flare: 0.05,
      wheelRadius: 0.3,
      wheelWidth: 0.2,
      frontAxle: -1.12,
      rearAxle: 1.18,
      wing: 0,
      wingWidth: 1.3,
      wingHeight: 0.08,
      sideIntakes: false,
      roofScoop: false,
      diffuser: false,
      splitter: false,
      lights: 'round',
      canopy: 'notch',
      stripe: 'none',
    },
    defaults: {
      primary: '#3fbfa0',
      secondary: '#f2f4f8',
      finish: 'gloss',
      wheelStyle: 'turbine',
      wheelColor: '#d8dce4',
      decal: 'none',
      raceNumber: 21,
      spoiler: false,
      tint: false,
    },
  },
  {
    id: 'brander-v8',
    name: 'Brander V8',
    make: 'Halloway',
    carClass: 'muscle',
    price: 9500,
    unlockLevel: 2,
    blurb: 'All torque, no manners. Point it straight and hold on.',
    stats: {
      topSpeed: 80,
      acceleration: 82,
      braking: 58,
      handling: 54,
      grip: 60,
      weight: 1680,
      downforce: 22,
      drift: 86,
      nitro: 0,
    },
    design: {
      length: 4.86,
      width: 1.98,
      height: 1.34,
      rideHeight: 0.14,
      cabinCenter: 0.6,
      cabinLength: 1.76,
      cabinWidth: 1.56,
      cabinRise: 0.28,
      noseTaper: 0.9,
      tailTaper: 0.94,
      flare: 0.14,
      wheelRadius: 0.36,
      wheelWidth: 0.3,
      frontAxle: -1.52,
      rearAxle: 1.5,
      wing: 1,
      wingWidth: 1.66,
      wingHeight: 0.12,
      sideIntakes: false,
      roofScoop: true,
      diffuser: false,
      splitter: true,
      lights: 'stacked',
      canopy: 'notch',
      stripe: 'dual',
    },
    defaults: {
      primary: '#1c3f8f',
      secondary: '#e8eaee',
      finish: 'gloss',
      wheelStyle: 'dish',
      wheelColor: '#0e1014',
      decal: 'stripes',
      raceNumber: 44,
      spoiler: false,
      tint: true,
    },
  },

  /* -------------------------------- MID -------------------------------- */
  {
    id: 'tessera-gtx',
    name: 'Tessera GTX',
    make: 'Vantis',
    carClass: 'gt',
    price: 18500,
    unlockLevel: 4,
    blurb: 'Endurance-bred GT. Immense stability under braking.',
    stats: {
      topSpeed: 84,
      acceleration: 78,
      braking: 88,
      handling: 81,
      grip: 86,
      weight: 1420,
      downforce: 68,
      drift: 48,
      nitro: 0,
    },
    design: {
      length: 4.68,
      width: 2.0,
      height: 1.2,
      rideHeight: 0.1,
      cabinCenter: 0.52,
      cabinLength: 1.66,
      cabinWidth: 1.5,
      cabinRise: 0.26,
      noseTaper: 0.6,
      tailTaper: 0.74,
      flare: 0.18,
      wheelRadius: 0.35,
      wheelWidth: 0.32,
      frontAxle: -1.44,
      rearAxle: 1.42,
      wing: 2,
      wingWidth: 1.8,
      wingHeight: 0.3,
      sideIntakes: true,
      roofScoop: false,
      diffuser: true,
      splitter: true,
      lights: 'wide',
      canopy: 'fastback',
      stripe: 'wedge',
    },
    defaults: {
      primary: '#e8e9ec',
      secondary: '#18b0d8',
      finish: 'gloss',
      wheelStyle: 'mesh',
      wheelColor: '#c8a23a',
      decal: 'blocks',
      raceNumber: 12,
      spoiler: true,
      tint: true,
    },
  },
  {
    id: 'skarn-4wd',
    name: 'Skarn 4WD',
    make: 'Norvik',
    carClass: 'rally',
    price: 22000,
    unlockLevel: 5,
    blurb: 'Loose-surface specialist. Shrugs off gravel and snow.',
    stats: {
      topSpeed: 74,
      acceleration: 85,
      braking: 79,
      handling: 84,
      grip: 90,
      weight: 1340,
      downforce: 30,
      drift: 74,
      nitro: 0,
    },
    design: {
      length: 4.4,
      width: 1.94,
      height: 1.4,
      rideHeight: 0.21,
      cabinCenter: 0.52,
      cabinLength: 1.78,
      cabinWidth: 1.5,
      cabinRise: 0.36,
      noseTaper: 0.8,
      tailTaper: 0.88,
      flare: 0.2,
      wheelRadius: 0.35,
      wheelWidth: 0.27,
      frontAxle: -1.3,
      rearAxle: 1.32,
      wing: 2,
      wingWidth: 1.8,
      wingHeight: 0.34,
      sideIntakes: false,
      roofScoop: true,
      diffuser: false,
      splitter: true,
      lights: 'round',
      canopy: 'notch',
      stripe: 'wedge',
    },
    defaults: {
      primary: '#1a63c8',
      secondary: '#f0c419',
      finish: 'gloss',
      wheelStyle: 'multispoke',
      wheelColor: '#d8b32a',
      decal: 'arrow',
      raceNumber: 9,
      spoiler: true,
      tint: false,
    },
  },
  {
    id: 'lumen-sx',
    name: 'Lumen SX',
    make: 'Aerin',
    carClass: 'sport',
    price: 26500,
    unlockLevel: 6,
    blurb: 'Mid-engined and razor sharp. Rewards a clean, committed line.',
    stats: {
      topSpeed: 82,
      acceleration: 84,
      braking: 82,
      handling: 90,
      grip: 84,
      weight: 1240,
      downforce: 52,
      drift: 58,
      nitro: 0,
    },
    design: {
      length: 4.38,
      width: 1.92,
      height: 1.16,
      rideHeight: 0.1,
      cabinCenter: 0.44,
      cabinLength: 1.44,
      cabinWidth: 1.4,
      cabinRise: 0.24,
      noseTaper: 0.52,
      tailTaper: 0.8,
      flare: 0.16,
      wheelRadius: 0.34,
      wheelWidth: 0.3,
      frontAxle: -1.3,
      rearAxle: 1.34,
      wing: 1,
      wingWidth: 1.66,
      wingHeight: 0.14,
      sideIntakes: true,
      roofScoop: false,
      diffuser: true,
      splitter: true,
      lights: 'slim',
      canopy: 'fastback',
      stripe: 'none',
    },
    defaults: {
      primary: '#2f3a48',
      secondary: '#ff8a3d',
      finish: 'metallic',
      wheelStyle: 'split5',
      wheelColor: '#1a1d24',
      decal: 'halftone',
      raceNumber: 33,
      spoiler: false,
      tint: true,
    },
  },

  /* -------------------------------- FAST ------------------------------- */
  {
    id: 'valdris-t',
    name: 'Valdris T',
    make: 'Aerin',
    carClass: 'super',
    price: 46000,
    unlockLevel: 8,
    blurb: 'Twin-turbo supercar. Brutal in a straight line, demanding in the wet.',
    stats: {
      topSpeed: 94,
      acceleration: 91,
      braking: 80,
      handling: 70,
      grip: 72,
      weight: 1460,
      downforce: 58,
      drift: 70,
      nitro: 35,
    },
    design: {
      length: 4.62,
      width: 2.02,
      height: 1.14,
      rideHeight: 0.09,
      cabinCenter: 0.42,
      cabinLength: 1.4,
      cabinWidth: 1.42,
      cabinRise: 0.22,
      noseTaper: 0.46,
      tailTaper: 0.72,
      flare: 0.2,
      wheelRadius: 0.36,
      wheelWidth: 0.34,
      frontAxle: -1.38,
      rearAxle: 1.4,
      wing: 2,
      wingWidth: 1.86,
      wingHeight: 0.26,
      sideIntakes: true,
      roofScoop: false,
      diffuser: true,
      splitter: true,
      lights: 'wide',
      canopy: 'fastback',
      stripe: 'wedge',
    },
    defaults: {
      primary: '#c9a227',
      secondary: '#15171c',
      finish: 'pearl',
      wheelStyle: 'turbine',
      wheelColor: '#15171c',
      decal: 'carbon',
      raceNumber: 5,
      spoiler: true,
      tint: true,
    },
  },
  {
    id: 'harrow-gt3',
    name: 'Harrow GT3',
    make: 'Halloway',
    carClass: 'track',
    price: 58000,
    unlockLevel: 10,
    blurb: 'Stripped, caged and aero-loaded. Built for one thing only.',
    stats: {
      topSpeed: 88,
      acceleration: 87,
      braking: 94,
      handling: 93,
      grip: 94,
      weight: 1240,
      downforce: 88,
      drift: 40,
      nitro: 0,
    },
    design: {
      length: 4.72,
      width: 2.06,
      height: 1.12,
      rideHeight: 0.07,
      cabinCenter: 0.5,
      cabinLength: 1.56,
      cabinWidth: 1.46,
      cabinRise: 0.22,
      noseTaper: 0.5,
      tailTaper: 0.68,
      flare: 0.24,
      wheelRadius: 0.36,
      wheelWidth: 0.36,
      frontAxle: -1.44,
      rearAxle: 1.44,
      wing: 3,
      wingWidth: 1.98,
      wingHeight: 0.4,
      sideIntakes: true,
      roofScoop: true,
      diffuser: true,
      splitter: true,
      lights: 'slim',
      canopy: 'fastback',
      stripe: 'dual',
    },
    defaults: {
      primary: '#16181e',
      secondary: '#e6362f',
      finish: 'matte',
      wheelStyle: 'multispoke',
      wheelColor: '#e6362f',
      decal: 'blocks',
      raceNumber: 88,
      spoiler: true,
      tint: true,
    },
  },
  {
    id: 'obsidia-x',
    name: 'Obsidia X',
    make: 'Norvik',
    carClass: 'hyper',
    price: 92000,
    unlockLevel: 14,
    blurb: 'Active aero hypercar. The highest ceiling in the game, if you can hold it.',
    stats: {
      topSpeed: 100,
      acceleration: 96,
      braking: 88,
      handling: 82,
      grip: 84,
      weight: 1390,
      downforce: 78,
      drift: 60,
      nitro: 55,
    },
    design: {
      length: 4.82,
      width: 2.08,
      height: 1.08,
      rideHeight: 0.07,
      cabinCenter: 0.44,
      cabinLength: 1.38,
      cabinWidth: 1.38,
      cabinRise: 0.2,
      noseTaper: 0.4,
      tailTaper: 0.64,
      flare: 0.26,
      wheelRadius: 0.37,
      wheelWidth: 0.36,
      frontAxle: -1.46,
      rearAxle: 1.48,
      wing: 3,
      wingWidth: 2.0,
      wingHeight: 0.32,
      sideIntakes: true,
      roofScoop: false,
      diffuser: true,
      splitter: true,
      lights: 'wide',
      canopy: 'bubble',
      stripe: 'wedge',
    },
    defaults: {
      primary: '#0f1116',
      secondary: '#7cf2d6',
      finish: 'pearl',
      wheelStyle: 'turbine',
      wheelColor: '#0f1116',
      decal: 'carbon',
      raceNumber: 1,
      spoiler: true,
      tint: true,
    },
  },
  {
    id: 'meridian-lmp',
    name: 'Meridian LMP',
    make: 'Aerin',
    carClass: 'prototype',
    price: 140000,
    unlockLevel: 18,
    blurb: 'Closed-cockpit prototype. Downforce so high it changes how you draw.',
    stats: {
      topSpeed: 97,
      acceleration: 94,
      braking: 98,
      handling: 97,
      grip: 97,
      weight: 960,
      downforce: 100,
      drift: 34,
      nitro: 40,
    },
    design: {
      length: 4.96,
      width: 2.1,
      height: 1.04,
      rideHeight: 0.05,
      cabinCenter: 0.46,
      cabinLength: 1.34,
      cabinWidth: 1.26,
      cabinRise: 0.2,
      noseTaper: 0.34,
      tailTaper: 0.56,
      flare: 0.3,
      wheelRadius: 0.36,
      wheelWidth: 0.38,
      frontAxle: -1.52,
      rearAxle: 1.54,
      wing: 3,
      wingWidth: 2.06,
      wingHeight: 0.42,
      sideIntakes: true,
      roofScoop: true,
      diffuser: true,
      splitter: true,
      lights: 'slim',
      canopy: 'bubble',
      stripe: 'wedge',
    },
    defaults: {
      primary: '#132a4a',
      secondary: '#f2f4f8',
      finish: 'gloss',
      wheelStyle: 'mesh',
      wheelColor: '#1b1e25',
      decal: 'arrow',
      raceNumber: 2,
      spoiler: true,
      tint: true,
    },
  },
];

export const getCar = (id: string): CarDefinition =>
  CARS.find((c) => c.id === id) ?? CARS[0];

export const DEFAULT_CAR_ID = CARS[0].id;

/* ------------------------------------------------------------------ */
/* Upgrades                                                            */
/* ------------------------------------------------------------------ */

const ramp = (base: number, steps = 5): number[] =>
  Array.from({ length: steps }, (_, i) => Math.round(base * Math.pow(1.82, i)));

export const UPGRADES: UpgradeDefinition[] = [
  {
    id: 'engine',
    label: 'Engine',
    description: 'Forced induction and mapping. More power everywhere.',
    maxLevel: 5,
    costs: ramp(1400),
    effects: [
      { acceleration: 3, topSpeed: 2 },
      { acceleration: 6, topSpeed: 4 },
      { acceleration: 10, topSpeed: 6 },
      { acceleration: 14, topSpeed: 9 },
      { acceleration: 19, topSpeed: 12 },
    ],
  },
  {
    id: 'transmission',
    label: 'Transmission',
    description: 'Closer ratios and faster shifts off the corner.',
    maxLevel: 5,
    costs: ramp(1100),
    effects: [
      { acceleration: 2 },
      { acceleration: 4, topSpeed: 1 },
      { acceleration: 7, topSpeed: 2 },
      { acceleration: 10, topSpeed: 4 },
      { acceleration: 13, topSpeed: 6 },
    ],
  },
  {
    id: 'brakes',
    label: 'Brakes',
    description: 'Carbon-ceramic discs. Brake later, every lap.',
    maxLevel: 5,
    costs: ramp(1000),
    effects: [
      { braking: 4 },
      { braking: 8 },
      { braking: 13 },
      { braking: 18 },
      { braking: 24 },
    ],
  },
  {
    id: 'tires',
    label: 'Tires',
    description: 'Softer compound. The single biggest grip gain.',
    maxLevel: 5,
    costs: ramp(1300),
    effects: [
      { grip: 4, handling: 1 },
      { grip: 8, handling: 2 },
      { grip: 13, handling: 4 },
      { grip: 18, handling: 6 },
      { grip: 24, handling: 8 },
    ],
  },
  {
    id: 'suspension',
    label: 'Suspension',
    description: 'Adjustable dampers and anti-roll. Sharper direction change.',
    maxLevel: 5,
    costs: ramp(1200),
    effects: [
      { handling: 4, drift: -2 },
      { handling: 8, drift: -4 },
      { handling: 12, grip: 2, drift: -6 },
      { handling: 17, grip: 4, drift: -8 },
      { handling: 22, grip: 6, drift: -10 },
    ],
  },
  {
    id: 'aero',
    label: 'Aerodynamics',
    description: 'Splitter, floor and wing. Grip that grows with speed.',
    maxLevel: 5,
    costs: ramp(1600),
    effects: [
      { downforce: 6, topSpeed: -1 },
      { downforce: 13, topSpeed: -2 },
      { downforce: 21, topSpeed: -2, handling: 2 },
      { downforce: 30, topSpeed: -3, handling: 4 },
      { downforce: 40, topSpeed: -4, handling: 6 },
    ],
  },
  {
    id: 'weight',
    label: 'Weight',
    description: 'Carbon panels and a stripped interior. Less mass, more of everything.',
    maxLevel: 5,
    costs: ramp(1800),
    effects: [
      { weight: -40, acceleration: 2, handling: 1 },
      { weight: -85, acceleration: 4, handling: 3 },
      { weight: -135, acceleration: 7, handling: 5, braking: 2 },
      { weight: -190, acceleration: 10, handling: 8, braking: 4 },
      { weight: -250, acceleration: 14, handling: 11, braking: 6 },
    ],
  },
];

export const getUpgrade = (id: UpgradeId): UpgradeDefinition =>
  UPGRADES.find((u) => u.id === id)!;

export const EMPTY_UPGRADES: Record<UpgradeId, number> = {
  engine: 0,
  transmission: 0,
  brakes: 0,
  tires: 0,
  suspension: 0,
  aero: 0,
  weight: 0,
};

/** Applies the owned upgrade levels to a base stat block. */
export const applyUpgrades = (
  base: CarStats,
  levels: Record<UpgradeId, number>,
): CarStats => {
  const out: CarStats = { ...base };
  for (const up of UPGRADES) {
    const level = levels[up.id] ?? 0;
    if (level <= 0) continue;
    const effect = up.effects[Math.min(level, up.maxLevel) - 1];
    for (const [key, value] of Object.entries(effect) as Array<[keyof CarStats, number]>) {
      out[key] = out[key] + value;
    }
  }
  // Clamp the designer-scale stats; weight has its own sane floor.
  const clampStat = (v: number) => Math.max(1, Math.min(120, v));
  out.topSpeed = clampStat(out.topSpeed);
  out.acceleration = clampStat(out.acceleration);
  out.braking = clampStat(out.braking);
  out.handling = clampStat(out.handling);
  out.grip = clampStat(out.grip);
  out.downforce = Math.max(0, Math.min(140, out.downforce));
  out.drift = Math.max(5, Math.min(120, out.drift));
  out.weight = Math.max(620, out.weight);
  return out;
};

/** Aggregate 0-100 rating used for sorting and the "PR" badge. */
export const performanceRating = (stats: CarStats): number => {
  const massFactor = 1 - Math.min(0.35, (stats.weight - 900) / 2600);
  const raw =
    stats.topSpeed * 0.24 +
    stats.acceleration * 0.24 +
    stats.handling * 0.2 +
    stats.grip * 0.18 +
    stats.braking * 0.14 +
    stats.downforce * 0.08;
  return Math.round(raw * (0.86 + massFactor * 0.2));
};

export const upgradeCost = (id: UpgradeId, currentLevel: number): number | null => {
  const up = getUpgrade(id);
  if (currentLevel >= up.maxLevel) return null;
  return up.costs[currentLevel];
};
